import 'package:owllangu/words.dart';

class ApiHelper {

  ApiHelper._privateConstructor();

  static final ApiHelper instance = ApiHelper._privateConstructor();

  List<EngRuWords> queryAllWords() {
    return words;
  }

  final words = <EngRuWords>[
    EngRuWords("absorbed", "поглощенный", 0, 0, 0),
    EngRuWords("accomplish", "выполнять / совершать", 0, 0, 0),

    EngRuWords("contented", "довольный / удовлетворенный", 0, 0, 0),

    EngRuWords("hesitate", "стесняться / колебаться", 0, 0, 0),
    EngRuWords("humble", "смиренный / покорный / простой", 0, 0, 0),
    EngRuWords("inch", "дюйм", 0, 0, 0),
    EngRuWords("inconvenience", "неудобство", 0, 0, 0),
    EngRuWords("insight", "понимание / интуиция", 0, 0, 0),
    EngRuWords("insincence", "неискренний", 0, 0, 0),
    EngRuWords("interfere", "вмешиваться", 0, 0, 0),
    EngRuWords("itch", "зуд", 0, 0, 0),
    EngRuWords("itching", "зудящий", 0, 0, 0),
    EngRuWords("jealous", "ревнивый", 0, 0, 0),
    EngRuWords("jolt", "удар / толчок", 0, 0, 0),
    EngRuWords("jubilant", "ликующий", 0, 0, 0),
    EngRuWords("Kindness", "доброжелательность", 0, 0, 0),
    EngRuWords("lavish", "щедрый / расточительный", 0, 0, 0),
    EngRuWords("merely", "просто / только", 0, 0, 0),
    EngRuWords("modesty", "скромность", 0, 0, 0),
    EngRuWords("mouthpiece", "микрофон / мундштук", 0, 0, 0),
    EngRuWords("nasty", "неприятный / противный", 0, 0, 0),
    EngRuWords("nested", "вложенный", 0, 0, 0),
    EngRuWords("notable", "примечательный", 0, 0, 0),
    EngRuWords("nudge", "подталкивать", 0, 0, 0),
    EngRuWords("obstacle", "препятствие", 0, 0, 0),
    EngRuWords("obviosly", "очивидно", 0, 0, 0),
    EngRuWords("pace", "темп", 0, 0, 0),
    EngRuWords("particularly", "в частности / особенно", 0, 0, 0),
    EngRuWords("peer", "равный / сверстники / всматриваться", 0, 0, 0),
    EngRuWords("perceive", "воспринимать / чувствовать / ощущать", 0, 0, 0),
    EngRuWords("perplexed", "недоумевающий / запутанный", 0, 0, 0),
    EngRuWords("perseverance", "усидчивость / настойчивость", 0, 0, 0),
    EngRuWords("pillar", "столб", 0, 0, 0),
    EngRuWords("potion", "зелье", 0, 0, 0),
    EngRuWords("prescribe", "предписать / прописывать лекарство", 0, 0, 0),
    EngRuWords("profound", "глубокий", 0, 0, 0),
    EngRuWords("prudence", "предусмотрительность / благоразумие", 0, 0, 0),
    EngRuWords("racket", "вести шумный образ жизни", 0, 0, 0),
    EngRuWords("recession", "спад / падение", 0, 0, 0),
    EngRuWords("regardless", "несмотря на", 0, 0, 0),
    EngRuWords("reinforce", "усиливать", 0, 0, 0),
    EngRuWords("rewind", "перемотать", 0, 0, 0),
    EngRuWords("rewiring", "переадресация", 0, 0, 0),
    EngRuWords("ripe", "созревший / зрелый", 0, 0, 0),
    EngRuWords("roar", "реветь / рычать", 0, 0, 0),
    EngRuWords("savor", "смаковать / наслаждаться", 0, 0, 0),
    EngRuWords("seize", "воспользоваться", 0, 0, 0),
    EngRuWords("shape", "форма / облик", 0, 0, 0),
    EngRuWords("shimmering", "мерцающий", 0, 0, 0),
    EngRuWords("shrinking", "сжимающийся", 0, 0, 0),
    EngRuWords("sidetracked", "отвлекаться", 0, 0, 0),
    EngRuWords("sill", "подоконник", 0, 0, 0),
    EngRuWords("singling out", "выделять", 0, 0, 0),
    EngRuWords("skinny", "тощий", 0, 0, 0),
    EngRuWords("snore", "храп", 0, 0, 0),
    EngRuWords("solid", "твердый / прочный", 0, 0, 0),
    EngRuWords("spiritual", "духовный / религиозный", 0, 0, 0),
    EngRuWords("spit", "плевок / слюна", 0, 0, 0),
    EngRuWords("spot", "пятно / капля", 0, 0, 0),
    EngRuWords("spray", "спрей / брызки / распылять", 0, 0, 0),
    EngRuWords("strolls over", "бродить / прогуливаться", 0, 0, 0),
    EngRuWords("struggled", "изо всех сил (бороться)", 0, 0, 0),
    EngRuWords("stubbornly", "упорно", 0, 0, 0),
    EngRuWords("survey", "опрос", 0, 0, 0),
    EngRuWords("swivell", "поворотливый / вращающийся", 0, 0, 0),
    EngRuWords("tape", "лента / приклеивать", 0, 0, 0),
    EngRuWords("temptation", "искушение / соблазн", 0, 0, 0),
    EngRuWords("thin", "тонкий / худой", 0, 0, 0),
    EngRuWords("thorough", "тщательный", 0, 0, 0),
    EngRuWords("throgh", "хотя / однако", 0, 0, 0),
    EngRuWords("tiredness", "усталость / утомление", 0, 0, 0),
    EngRuWords("to what extent", "До какой степени", 0, 0, 0),
    EngRuWords("torch", "факел / горелка", 0, 0, 0),
    EngRuWords("treat", "рассматривать / лечить / относиться", 0, 0, 0),
    EngRuWords("untidy", "неопрятный / беспорядочный", 0, 0, 0),
    EngRuWords("worthwhile", "стоит / стоящий", 0, 0, 0),
    EngRuWords("yell", "вопить / кричать ", 0, 0, 0),
    EngRuWords("zest", "цедра / изюминка / интерес", 0, 0, 0),
    EngRuWords("intensify", "активизировать / усиливать", 0, 0, 0),
    EngRuWords("enhance", "усилить / повышать", 0, 0, 0),
    EngRuWords("utilize", "использовать", 0, 0, 0),
    EngRuWords("thwart", "пресекать / разрушать", 0, 0, 0),
    EngRuWords("entirely", "полностью", 0, 0, 0),
    EngRuWords("strive", "прилагать усилия", 0, 0, 0),
    EngRuWords("tidy", "аккуратный", 0, 0, 0)
  ];

}