class EngRuWords {
  EngRuWords(this.eng, this.ru);

  final String eng;
  final String ru;

  @override
  String toString() => 'EngRuWords[$eng, $ru]';
}

var words = <EngRuWords>[
  EngRuWords("	absorbed	", "	поглощенный	"),
  EngRuWords("	accomplish	", "	выполнять / совершать	"),
  EngRuWords("	accomplishment	", "	достижение	"),
  EngRuWords("	adjust	", "	регулировать	"),
  EngRuWords("	admire	", "	восхищаться / любоваться	"),
  EngRuWords("	AFFILIATE	", "	филиал / компаньон	"),
  EngRuWords("	affiliated	", "	кооперироваться	"),
  EngRuWords("	amend	", "	изменять / вносить правки	"),
  EngRuWords("	anxiety	", "	тревога / беспокойство	"),
  EngRuWords("	anxious	", "	озабоченный / тревожный	"),
  EngRuWords("	appreciation	", "	признательность / оценка / понимание	"),
  EngRuWords("	as through	", "	как через	"),
  EngRuWords("	ashamed	", "	совестно	"),
  EngRuWords("	assignment	", "	назначение	"),
  EngRuWords("	authentic	", "	аутентичный / подлинный	"),
  EngRuWords("	barely	", "	едва / лишь	"),
  EngRuWords("	binge	", "	выпивка / кутеж	"),
  EngRuWords("	blessing	", "	благословение	"),
  EngRuWords("	brag	", "	хвастать	"),
  EngRuWords("	broaden	", "	расширить	"),
  EngRuWords("	bulk	", "	масса / объем / большая часть	"),
  EngRuWords("	cage	", "	клетка	"),
  EngRuWords("	cheer up	", "	развеселить / взбодрить	"),
  EngRuWords("	claim	", "	запрос / требование / иск / претензия	"),
  EngRuWords("	consent	", "	согласие	"),
  EngRuWords("	contented	", "	довольный / удовлетворенный	"),
  EngRuWords("	creature	", "	существо / тварь	"),
  EngRuWords("	creep	", "	ползти / подкрадываться	"),
  EngRuWords("	cupboard	", "	шкаф / буфет	"),
  EngRuWords("	dedicate	", "	посвящать	"),
  EngRuWords("	deed	", "	дело / поступок	"),
  EngRuWords("	delight	", "	восторг / наслаждение	"),
  EngRuWords("	derive	", "	получать / извлекать	"),
  EngRuWords("	despair	", "	отчаяние	"),
  EngRuWords("	detention	", "	арест / задержание	"),
  EngRuWords("	disparate	", "	несоизмеримый	"),
  EngRuWords("	distant	", "	отдаленный / далекий	"),
  EngRuWords("	divisive	", "	разделяющий / вызывающий разногласия	"),
  EngRuWords("	drafting	", "	чертёжный	"),
  EngRuWords("	dull	", "	тупой / бестолковый	"),
  EngRuWords("	eagerly	", "	охотно	"),
  EngRuWords("	encourage	", "	поощрять	"),
  EngRuWords("	engage	", "	заниматься / привлекать	"),
  EngRuWords("	engagement	", "	обязательство / включение	"),
  EngRuWords("	enormous	", "	огромный	"),
  EngRuWords("	enroll	", "	записаться / регистрироваться	"),
  EngRuWords("	evidence	", "	доказательство	"),
  EngRuWords("	excuse	", "	оправдание	"),
  EngRuWords("	expression	", "	выражение / экспрессия	"),
  EngRuWords("	faith	", "	вера	"),
  EngRuWords("	fallacy	", "	ошибочность / заблуждение	"),
  EngRuWords("	favors	", "	одолжение	"),
  EngRuWords("	fellow	", "	человек / парень	"),
  EngRuWords("	fled	", "	бежать / спасаться	"),
  EngRuWords("	flinch	", "	вздрагивать	"),
  EngRuWords("	flourishing	", "	процветающий	"),
  EngRuWords("	forehead	", "	лоб	"),
  EngRuWords("	genuinely	", "	искренне / неподдельно	"),
  EngRuWords("	gloomy	", "	мрачный / угрюмый	"),
  EngRuWords("	grab	", "	схватить	"),
  EngRuWords("	grudge	", "	недоброжелательство / зависть	"),
  EngRuWords("	grunting	", "	хрюканье	"),
  EngRuWords("	Handouts	", "	раздаточные материалы	"),
  EngRuWords("	hesitate	", "	стесняться / колебаться	"),
  EngRuWords("	humble	", "	смиренный / покорный / простой	"),
  EngRuWords("	inch	", "	дюйм	"),
  EngRuWords("	inconvenience	", "	неудобство	"),
  EngRuWords("	insight	", "	понимание / интуиция	"),
  EngRuWords("	insincence	", "	неискренний	"),
  EngRuWords("	interfere	", "	вмешиваться	"),
  EngRuWords("	itch	", "	зуд	"),
  EngRuWords("	itching	", "	зудящий	"),
  EngRuWords("	jealous	", "	ревнивый	"),
  EngRuWords("	jolt	", "	удар / толчок	"),
  EngRuWords("	jubilant	", "	ликующий	"),
  EngRuWords("	Kindness	", "	доброжелательность	"),
  EngRuWords("	lavish	", "	щедрый / расточительный	"),
  EngRuWords("	merely	", "	просто / только	"),
  EngRuWords("	modesty	", "	скромность	"),
  EngRuWords("	mouthpiece	", "	микрофон / мундштук	"),
  EngRuWords("	nasty	", "	неприятный / противный	"),
  EngRuWords("	nested	", "	вложенный	"),
  EngRuWords("	notable	", "	примечательный	"),
  EngRuWords("	nudge	", "	подталкивать	"),
  EngRuWords("	obstacle	", "	препятствие	"),
  EngRuWords("	obviosly	", "	очивидно	"),
  EngRuWords("	pace	", "	темп	"),
  EngRuWords("	particularly	", "	в частности / особенно	"),
  EngRuWords("	peer	", "	равный / сверстники / всматриваться	"),
  EngRuWords("	perceive	", "	воспринимать / чувствовать / ощущать	"),
  EngRuWords("	perplexed	", "	недоумевающий / запутанный	"),
  EngRuWords("	perseverance	", "	усидчивость / настойчивость	"),
  EngRuWords("	pillar	", "	столб	"),
  EngRuWords("	potion	", "	зелье	"),
  EngRuWords("	prescribe	", "	предписать / прописывать лекарство	"),
  EngRuWords("	profound	", "	глубокий	"),
  EngRuWords("	prudence	", "	предусмотрительность / благоразумие	"),
  EngRuWords("	racket	", "	вести шумный образ жизни	"),
  EngRuWords("	recession	", "	спад / падение	"),
  EngRuWords("	regardless	", "	несмотря на	"),
  EngRuWords("	reinforce	", "	усиливать	"),
  EngRuWords("	rewind	", "	перемотать	"),
  EngRuWords("	rewiring	", "	переадресация	"),
  EngRuWords("	ripe	", "	созревший / зрелый	"),
  EngRuWords("	roar	", "	реветь / рычать	"),
  EngRuWords("	savor	", "	смаковать / наслаждаться	"),
  EngRuWords("	seize	", "	воспользоваться	"),
  EngRuWords("	shape	", "	форма / облик	"),
  EngRuWords("	shimmering	", "	мерцающий	"),
  EngRuWords("	shrinking	", "	сжимающийся	"),
  EngRuWords("	sidetracked	", "	отвлекаться	"),
  EngRuWords("	sill	", "	подоконник	"),
  EngRuWords("	singling out	", "	выделять	"),
  EngRuWords("	skinny	", "	тощий	"),
  EngRuWords("	snore	", "	храп	"),
  EngRuWords("	solid	", "	твердый / прочный	"),
  EngRuWords("	spiritual	", "	духовный / религиозный	"),
  EngRuWords("	spit	", "	плевок / слюна	"),
  EngRuWords("	spot	", "	пятно / капля	"),
  EngRuWords("	spray	", "	спрей / брызки / распылять	"),
  EngRuWords("	strolls over	", "	бродить / прогуливаться	"),
  EngRuWords("	struggled	", "	изо всех сил (бороться)	"),
  EngRuWords("	stubbornly	", "	упорно	"),
  EngRuWords("	survey	", "	опрос	"),
  EngRuWords("	swivell	", "	поворотливый / вращающийся	"),
  EngRuWords("	tape	", "	лента / приклеивать	"),
  EngRuWords("	temptation	", "	искушение / соблазн	"),
  EngRuWords("	thin	", "	тонкий / худой	"),
  EngRuWords("	thorough	", "	тщательный	"),
  EngRuWords("	throgh	", "	хотя / однако	"),
  EngRuWords("	tiredness	", "	усталость / утомление	"),
  EngRuWords("	to what extent	", "	До какой степени	"),
  EngRuWords("	torch	", "	факел / горелка	"),
  EngRuWords("	treat	", "	рассматривать / лечить / относиться	"),
  EngRuWords("	untidy	", "	неопрятный / беспорядочный	"),
  EngRuWords("	worthwhile	", "	стоит / стоящий	"),
  EngRuWords("	yell	", "	вопить / кричать 	"),
  EngRuWords("	zest	", "	цедра / изюминка / интерес	"),
  EngRuWords("	intensify	", "	активизировать / усиливать	"),
  EngRuWords("	enhance	", "	усилить / повышать	"),
  EngRuWords("	utilize	", "	использовать	"),
  EngRuWords("	thwart	", "	пресекать / разрушать	"),
  EngRuWords("	entirely	", "	полностью	"),
  EngRuWords("	strive	", "	прилагать усилия	"),
  EngRuWords("	tidy	", "	аккуратный	")
];
